### ISSUE TITLE
Script turns portrait images into landscape mode after conversion

### ISSUE THREAD

**Issue by liashchynskyi** [victordomingos/optimize-images#10]
Hi, @victordomingos 
After testing some images I found an interesting bug. If there are portrait images in directory then this tool turns them into landscape mode.
Any suggestions why it happens? 😺

**Comment by victordomingos** [comment]
Hi! Thanks for the report!

It certainly shouldn’t be happening. Can you please provide additional info?

- Python version
- Pillow version
- does it happen in all cases if one image is in portrait mode, or just in specific circumstances?

Best regards,
Victor

**Comment by liashchynskyi** [comment]
I tested it again and figured out that my Image Viewer (I use Picasa 3) on Windows is not showing images correctly 😄 
All is fine.
