### ISSUE TITLE
Specify Pillow as requirement in setup.py?

### ISSUE THREAD

**Issue by vascowhite** [victordomingos/optimize-images#2]
<strike>
PIL hasn't been updated since [2009](http://www.pythonware.com/products/pil/#pil117), whereas [pillow](https://pillow.readthedocs.io/) is under active development.

I think it would be a good idea to change, especially as you are using Python >= 3.6.
</strike>
I can put in a pull request if you wish.

This is a nice little utility which has saved me writing my own :) Thanks.

**Comment by vascowhite** [comment]
I just realised that you intend Pillow to be used. I installed into a virtualenv using Pipenv and got an error that PIL wasn't installed, so I raised this issue.
Do you think it would be better to put a requirement for pillow in setup.py? You already have piexif there, so I don't understand why Pillow isn't.

**Comment by victordomingos** [comment]
I guess the current setup.py may be improved. I have two separate requirements files, one for desktop and another for iOS/Pythonista. In Pythonista, you already have Pillow, and the bundled version cannot be upgraded, so it’s not included as a requirement for iOS. 

I will see if I can improve setup.py to make it a bit more clear and implement a more straightforward installation process.

**Comment by vascowhite** [comment]
I guess I wasn't thinking of the iOS part, it makes sense why you've done it that way now.
I think I was confused by the error message refering to PIL rather than Pillow. If I had installed globally rather than into a virtualenv I wouldn't have seen any error as I have Pillow installed.

**Comment by victordomingos** [comment]
I have just added some details to the setup.py file. If all works as it should, doing a pip install should select and install the correct Pillow version if it’s not running on iOS.
