### ISSUE TITLE
Command line icons not properly shown in Windows

### ISSUE THREAD

**Issue by jsh9** [victordomingos/optimize-images#21]
The red dot, the green check mark, and the red triangle do not show up properly in the command line of Windows.  (I'm referring to the screenshot in your README file.)

Can you use ASCII characters instead?  Thanks.

**Comment by victordomingos** [comment]
Yes, it is a known issue. In most platforms, it displays properly, but CMD (not sure about PowerShell) seems to have rather limited character set. Ideally, we would detect if the current shell does not support these Unicode symbols and respond accordingly, but I am not sure there is a way to do so.

**Comment by jsh9** [comment]
I just tried powershell, and it didn't show the icons properly.

Maybe you can simply detect the operating system, and use ASCII characters for Windows, and original icons for the other system?

**Comment by victordomingos** [comment]
Actually, a similar question has arisen before and at the time this was the solution put in place:

https://github.com/victordomingos/optimize-images/blob/dc6a0054079b989d5c29e37e33f6b73998b8e8a6/optimize_images/platforms.py#L13

I hope to be able to look into this issue in one or two weeks. It will be fixed.

**Comment by victordomingos** [comment]
Ok. Although there isn't still a fix for this, it's worth noting, meanwhile, that on Git Bash for Windows (Mingw64), this is already working as expected, displaying ASCII characters.

**Comment by victordomingos** [comment]
Should be fixed as of 86574c049e20259e2b7da049cafb8d95bb21afc4, which can be downloaded from GitHub right now. Please let me know if you still find any issues. 

In a few days, I will do some additional testing and then I will upload the updated version to PyPI.
