### ISSUE TITLE
Convert png to jpg regardless of size

### ISSUE THREAD

**Issue by wadebarrie** [victordomingos/optimize-images#27]
Would love to batch convert all pngs to jpgs and force delete original as part of my optimize/resize process. I tried using `optimize-images -cb -fd ./` but it did not convert my pngs which were 660kb.

**Comment by victordomingos** [comment]
Hi! You can also add an additional `-ca` or `--convert-all` command-line argument, which makes it convert all images to jpg.

**Comment by wadebarrie** [comment]
This was very helpful! Thanks!
