### ISSUE TITLE
[Feature Request] Docker support

### ISSUE THREAD

**Issue by hmqgg** [victordomingos/optimize-images#28]

**Comment by victordomingos** [comment]
Can you please provide some details, like a use case example and how docker would make it more useful?

**Comment by hmqgg** [comment]
**Example:**
```bash
docker run -v myImagesVolume:/data optimize-images
```
It will optimize newly created images automatically in `myImagesVolume` with `-wd` option.

**Why?**
Using Docker here for *optimize-images* helps it integrates other web applications using Docker, esp. for those use Volume to store static image files. It will have other advantages like every Docker apps, e.g. providing easier managed out of the box CI version of *optimize-images* on master branch without release.

**Comment by varnav** [comment]
Done!

https://github.com/varnav/optimize-images-docker

You can run it just like this:

```sh
docker run -d --name optimize-images -v /opt/imagedir/:/data --restart on-failure:10 --network none --security-opt no-new-privileges  varnav/optimize-images --watch-directory /data
```
Please test it. If it's good I will make a PR.

**Comment by victordomingos** [comment]
I still hadn’t the opportunity to test it (I will try soon), but I wonder if it wouldn’t be better to maintain it as separate project instead and add a mention in the docs. What do you think about it?

**Comment by varnav** [comment]
I don't know, it's up to you!

Best thing about docker version is this case - it performs better because of mozpeg inside.

**Comment by victordomingos** [comment]
That's interesting, indeed, and I will explore that possibility for my personal use. In one of my systems, I have replaced Python with Python-SIMD, which also produced a nice boost.

But it is the kind of approach that I prefer to keep separate, since Optimize Images proposes itself as an almost pure Python application (being Pillow the only non pure Python requirement). I have made the decision to keep this approach and to try to make any future requirements optional, in order to keep it compatible with some limited environments like Pythonista for iOS.

**Comment by varnav** [comment]
It's not just faster. It compresses better.

And this is what Docker is for - you can change things like this leaving host system intact.

**Comment by victordomingos** [comment]
I see. Thanks for your idea and your effort. I hear a lot about Docker on Linux, but last time I checked it seemed to be a bit less interesting on macOS (Which I tend to use most of the time), in terms of performance. I will check it again soon. 

Do you mind if I add a paragraph in Optimize Image's documentation referring you new Optimize Images Docker as a related project? I think it could be useful for potential users.

**Comment by varnav** [comment]
I'm running under windows where it's supposed to be the worst, especially with file system mapping, but it's actually pretty fast.

Please link to my project, thanks!

**Comment by victordomingos** [comment]
I have just added a mention to Optimize Images Docker in the docs:

https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md#related-projects
https://github.com/victordomingos/optimize-images/blob/master/docs/docs_PT.md#projetos-relacionados
