### ISSUE TITLE
Skips png's

### ISSUE THREAD

**Issue by Evert-Arends** [victordomingos/optimize-images#34]
**Describe the bug**
The app skips pngs by default
In de readme it says: "tries to optimize each encoder's settings for maximum space reduction and applies the maximum ZLIB compression on PNG.", But in reality it just says:

```
🔴  [SKIPPED] redacted.png                                                                                      
----------------------------------------

   Processed 1 files (1.2 MB) in 3.0s (0.3 f/s).
   Optimized 0 files.
   Average savings: 0.0 B per optimized file
   Total space saved: 0.0 B / 0.0%
```
**To Reproduce**
1.   optimize-images mypng.png
2.   ???
3.   Profit

**Expected behavior**
A smaller png

**Desktop (please complete the following information):**
 - OS: Manjaro 21.0.2 Ornara
 - Python 3.9
 - Optimize Images version 1.4.0

**Comment by victordomingos** [comment]
Hi! When it shows a "SKIPPED" task report, it means that the app was not able to reduce the size of that specific image under the current settings. You can check this by making a separate copy of the image (it should already be a copy) and experiment with more aggressive settings, like `-rc`/` --reduce-colors`  or  `-cb`/`--convert-big`. It will probably result in a different report line.

**Comment by Evert-Arends** [comment]
Thanks for replying so fast, really appreciate it.

In that case please close this issue :facepalm:
