### ISSUE TITLE
Ability to Suppress Output

### ISSUE THREAD

**Issue by snowsquizy** [victordomingos/optimize-images#35]
**Is your feature request related to a problem? Please describe.**  
I want to run the utility without any output unless an error occurs

**Describe the solution you'd like**  
Command line option to suppress output

**Additional context**  
This utility is being called from within another program with logging enabled.  This will quickly increase the size of the log without any benefit. The display of errors should still occur.

Optimize Images 1.5.0

Running environment:
  - Location: /usr/local/bin/optimize-images
  - Pillow 8.3.2
  - Piexif 1.1.3
  - Python 3.7.3 (/usr/bin/python3)

Optional packages:
  - Watchdog 2.1.2

**Comment by victordomingos** [comment]
Hi! Thanks for taking your time to place this issue. It is both a simple and a good idea, and I will probably implement it soon.

**Comment by victordomingos** [comment]
Hi! I have just merged 5cdebb74850c0aa324dae8565e0fdf6a3f8ca697 (contributed by @derenix) which I think includes the feature you were asking for (currently using the command-line argument `--quiet`, but there could be some minor changes before a final release). Please take a look and let us know if it works for you.
