### ISSUE TITLE
Error with Pillow 8.2.0 and python 3.10

### ISSUE THREAD

**Issue by albertopasqualetto** [victordomingos/optimize-images#39]
Pyhton 3.10 is incompatible with pillow 8.2.0 as described here https://pillow.readthedocs.io/en/latest/installation.html
so it won't `pip install`.

**Comment by victordomingos** [comment]
Thanks for the heads-up! It would be nice to provide a wider range of possibilities. I suppose there won't be any major incompatibilities with recent major Pillow versions, at least since v.7, since we are using just a tiny subset of it, but some testing will be needed.

**Comment by victordomingos** [comment]
V.1.5.1 (released today) should fix this issue. 
Please let me know if it solved the issue for you.

**Comment by albertopasqualetto** [comment]
Yes, it is working now.
