### ISSUE TITLE
img_optimize_png.py not parsing temp path correctly 

### ISSUE THREAD

**Issue by Tenfleques** [victordomingos/optimize-images#9]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/optimize_images/img_optimize_png.py", line 125, in optimize_png
    img.save(temp_file_path, optimize=True, format=result_format)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 1966, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/~temp~woocommerce-placeholder.png'

**Comment by Tenfleques** [comment]
I copied this control from img_optimize_jpg.py to img_optimize_png.py 
 ```
if folder == '':
        folder = os.getcwd()
```
but I think you need to find out why `os.path.split(t.src_path) `is not giving you the folder pjath

**Comment by victordomingos** [comment]
Just a quick notice to let you know that, on the latest commit (not yet available in PyPI), I have implemented in-memory buffers using BytesIO, instead of in-disk temporary files.
